language: java

install:
 - docker-compose build
 - docker login -u $login -p $pwddock
 - docker image ls
 - docker tag students_solution_api aguyot/api
 - docker tag students_solution_bdd aguyot/bdd
 - docker tag students_solution_rp aguyot/rp
 - docker push aguyot/bdd
 - docker push aguyot/rp
 - docker push aguyot/api

cache:
  directories:
    - "$HOME/.m2/repository"