---
# tasks file for roles/utils
- name: Block specific IP
  iptables:
    chain: INPUT
    policy: DROP
  become: yes
- name: Accept 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  become: yes
- name: Accept 22
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
  become: yes